import reflex as rx
from Tocc.styles.styles import Size, Spacing
from Tocc.styles.colors import Color, TextColor

class Spline(rx.Component):
    library = "@splinetool/react-spline"
    lib_dependencies: list[str] = ["@splinetool/runtime@1.5.5"]
    tag = "Spline"
    is_default = True
    scene: rx.Var[str]

    @classmethod
    def spline_demo(cls):
        return cls.create(scene="https://prod.spline.design/1mjBPr5ZXdyYk6ey/scene.splinecode")

def header() -> rx.Component:
    return rx.vstack(
        rx.hstack(
            rx.vstack(
                rx.text("Conoce un poco de nosotros", size="9"),
                rx.vstack(
                    rx.text("Tocc es una empresa dedicada a la creación de experiencias digitales,", size="5"),
                    rx.text("donde la tecnología y el diseño se unen para ofrecer soluciones innovadoras.", size="5"),
                    spacing = "0",
                ),
                rx.link(
                    rx.button(
                        "Conócenos",
                        size="4",
                        bg = Color.PURPLE.value,
                        color="white",
                        width="300px",
                        border="none",
                        box_shadow = "none",
                    ),
                    href="/nosotros",
                ),
                align_items="center",
                width="60%",  
                bg = Color.LILA.value,
                spacing="4",
                border_radius="10px",
                padding_y=Size.SMALL.value, 
            ), 
            rx.spacer(flex="0.8"),
            rx.box(
                Spline.spline_demo(),
                width="400px",  
                height="400px",
            ),
            width="100%",
            bg = Color.PURPLE.value,
            padding_x=Size.VERY_BIG.value,
            padding_y=Size.SMALL.value,
            align_items="center",
            border_radius="10px",
        ),
        rx.vstack(
            rx.text("Servicios integrales a la medida y su necesidad", 
                        size="8", 
                        color=TextColor.LIGHT.value,
                        font_weight="bold",
                        align="center",
                        weight="bold",
                        ),
            rx.flex(
                rx.vstack(
                    rx.image(src="/desarrollo.png",
                            width="100%", 
                            height="auto", 
                            alt="Desarrollo software y soluciones digitales",
                            border_radius="10px",
                            ),
                    rx.text("Desarrollo de software y soluciones digitales",
                            size="4",
                            color=TextColor.LIGHT.value,
                            font_weight="bold",
                            align="center",
                            ),
                bg = Color.LILA.value,
                border_radius="10px",
                padding_x=Size.DEFAULT.value,
                padding_y=Size.DEFAULT.value,
                _hover={
                    "transform": "scale(1.05)",
                    "transition": "transform 0.3s ease-in-out",
                },
                ),
                rx.vstack(
                    rx.image(src="/ciberseguridad.png",
                            width="100%", 
                            height="auto", 
                            alt="Cirberseguridad y protección de datos",
                            border_radius="10px",
                            ),
                    rx.text("Ciberseguridad y protección de datos",
                            size="4",
                            color=TextColor.LIGHT.value,
                            font_weight="bold",
                            align="center",
                            ),
                bg = Color.LILA.value,
                border_radius="10px",
                padding_x=Size.DEFAULT.value,
                padding_y=Size.DEFAULT.value,
                _hover={
                    "transform": "scale(1.05)",
                    "transition": "transform 0.1s ease-in-out",
                },
                ),
                rx.vstack(
                    rx.image(src="/asesorias.png",
                            width="100%", 
                            height="auto", 
                            alt="Consultorías y asesorías tecnológicas",
                            border_radius="10px",
                            ),
                    rx.text("Consultorías y asesorías tecnológicas",
                            size="4",
                            color=TextColor.LIGHT.value,
                            font_weight="bold",
                            align="center",
                            ),
                bg = Color.LILA.value,
                border_radius="10px",
                padding_x=Size.DEFAULT.value,
                padding_y=Size.DEFAULT.value,
                _hover={
                    "transform": "scale(1.05)",
                    "transition": "transform 0.3s ease-in-out",
                },
                ),
                rx.vstack(
                    rx.image(src="/harware.png",
                            width="100%", 
                            height="auto", 
                            alt="Soluciones de hardware y equipamiento tecnológico",
                            border_radius="10px",
                            ),
                    rx.text("Soluciones de hardware y equipamiento tecnológico",
                            size="4",
                            color=TextColor.LIGHT.value,
                            font_weight="bold",
                            align="center",
                            ),
                bg = Color.LILA.value,
                border_radius="10px",
                padding_x=Size.DEFAULT.value,
                padding_y=Size.DEFAULT.value,
                _hover={
                    "transform": "scale(1.05)",
                    "transition": "transform 0.3s ease-in-out",
                },
                ),
                spacing="4",
                width="100%",
                padding_x=Size.DEFAULT.value,
                padding_y=Size.DEFAULT.value,
            ),
            rx.link(
                    rx.button(
                        "Todos los servicios",
                        rx.icon("square-arrow-right"),
                        size="4",
                        bg = Color.LILA.value,
                        color="white",
                        width="100%",
                        border="none",
                        box_shadow = "none",
                        padding_y=Size.SMALL.value,
                    ),
                    href="/servicios",
                ),
            width="100%",
            bg = Color.PURPLE.value,
            padding_x=Size.VERY_BIG.value,
            padding_y=Size.BIG.value,
            align_items="center",
            border_radius="10px",
        ),
        rx.vstack(
            rx.vstack(
                rx.text("¿Tienes dudas?", size="8"),
                rx.text("Contáctanos y te ayudaremos a resolverlas.", size="5"),
                align="center",
                width="100%",
                bg=Color.LILA.value,
                padding_x=Size.DEFAULT.value,
                padding_y=Size.DEFAULT.value,
                border_radius="10px",
            ),
            rx.link(
                rx.button(
                    "Contáctanos",
                    size="4",
                    bg = Color.LILA.value,
                    color="white",
                    width="100%",
                    border="none",
                    box_shadow = "none",
                    padding_x=Size.DEFAULT.value,
                    padding_y=Size.DEFAULT.value,
                ),
                href="/contactanos",
            ),
            width="100%",
            bg = Color.PURPLE.value,
            padding_x=Size.VERY_BIG.value,
            padding_y=Size.BIG.value,
            align_items="center",
            border_radius="10px",
        ),
        width="100%",
    )
            